#!/usr/bin/env python3
"""
scripts/seed_demo_data.py
=========================
Populate the dashboard with realistic demo data by running ~20 failed-payment
records through the REAL agent pipeline via POST /webhooks/razorpay.

Every audit_log row is generated by the actual classifier -> guardrails ->
decision -> executor chain, so reasoning, messages, and outcomes are authentic.

Usage
-----
1. Start your local FastAPI server:
       cd d:\Razorpay
       uvicorn backend.main:app --reload --port 8000

2. Set DISABLE_DEDUP=true in backend/.env so the 24-hour dedup window does not
   skip most records when you submit the whole batch in one go.

3. From the repo root run:
       python scripts/seed_demo_data.py

   Override the target URL if pointing at Render:
       $env:SEED_API_URL = "https://your-render-backend.onrender.com"
       python scripts/seed_demo_data.py

4. After seeding, flip DISABLE_DEDUP back to false in backend/.env (or
   remove it from Render env vars) so live traffic gets dedup protection again.

Auth note
---------
The /webhooks/razorpay endpoint uses HMAC signature verification.
When RAZORPAY_WEBHOOK_SECRET=mock_secret_for_now (local dev default) the
signature check is skipped, so no token is needed.
For Render: keep that env var set during seeding, then restore the real secret.

Clear existing test data first (Supabase SQL editor)
-----------------------------------------------------
    DELETE FROM audit_log      WHERE merchant_id = '<your-merchant-uuid>';
    DELETE FROM failed_payments WHERE merchant_id = '<your-merchant-uuid>';

Find your merchant UUID: Supabase -> Table Editor -> merchants -> id column.
Set it as an env var before running:
    $env:SEED_MERCHANT_ID = "<your-merchant-uuid>"
"""

import os
import sys
import time
from datetime import datetime, timedelta, timezone

import requests

# ---------------------------------------------------------------------------
API_URL     = os.environ.get("SEED_API_URL", "http://localhost:8000")
MERCHANT_ID = os.environ.get("SEED_MERCHANT_ID", "")
WEBHOOK_URL = f"{API_URL}/webhooks/razorpay"

NOW = datetime.now(timezone.utc)

def _ts(hours_ago: float) -> str:
    return (NOW - timedelta(hours=hours_ago)).isoformat()


SEED_RECORDS = [
    # High-tier retryable -------------------------------------------------
    {"customer_id": "CUST-MEERA-001",  "customer_name": "Meera Krishnamurthy",   "customer_email": "meera.k@example.in",   "customer_tier": "high", "amount": 2499.00, "failure_reason": "card_declined",     "failed_at": _ts(72), "_note": "High-tier card declined"},
    {"customer_id": "CUST-ARJUN-002",  "customer_name": "Arjun Venkataraman",    "customer_email": "arjun.v@example.in",   "customer_tier": "high", "amount": 1850.00, "failure_reason": "bank_timeout",       "failed_at": _ts(68), "_note": "Bank timeout high tier"},
    {"customer_id": "CUST-PRIYA-003",  "customer_name": "Priya Subramaniam",     "customer_email": "priya.sub@example.in", "customer_tier": "high", "amount": 3200.00, "failure_reason": "insufficient_funds", "failed_at": _ts(60)},
    # Low/mid retryable ---------------------------------------------------
    {"customer_id": "CUST-RAVI-004",   "customer_name": "Ravi Shankar Gupta",    "customer_email": "ravi.gupta@example.in","customer_tier": "low",  "amount":  499.00, "failure_reason": "card_declined",      "failed_at": _ts(55)},
    {"customer_id": "CUST-DIVYA-005",  "customer_name": "Divya Nambiar",         "customer_email": "divya.n@example.in",   "customer_tier": "low",  "amount":  799.00, "failure_reason": "bank_timeout",       "failed_at": _ts(50)},
    {"customer_id": "CUST-SANJAY-006", "customer_name": "Sanjay Mehrotra",       "customer_email": "sanjay.m@example.in",  "customer_tier": "high", "amount": 1200.00, "failure_reason": "card_declined",      "failed_at": _ts(48)},
    {"customer_id": "CUST-ANANYA-007", "customer_name": "Ananya Bhattacharya",   "customer_email": "ananya.b@example.in",  "customer_tier": "low",  "amount":  299.00, "failure_reason": "insufficient_funds", "failed_at": _ts(45)},
    {"customer_id": "CUST-VIKRAM-008", "customer_name": "Vikram Malhotra",       "customer_email": "vikram.m@example.in",  "customer_tier": "high", "amount": 4500.00, "failure_reason": "bank_timeout",       "failed_at": _ts(42)},
    {"customer_id": "CUST-SUNITA-009", "customer_name": "Sunita Pillai",         "customer_email": "sunita.p@example.in",  "customer_tier": "low",  "amount":  650.00, "failure_reason": "card_declined",      "failed_at": _ts(38)},
    {"customer_id": "CUST-ROHIT-010",  "customer_name": "Rohit Agarwal",         "customer_email": "rohit.a@example.in",   "customer_tier": "high", "amount": 2100.00, "failure_reason": "card_declined",      "failed_at": _ts(35)},
    {"customer_id": "CUST-KAVITHA-011","customer_name": "Kavitha Rajan",         "customer_email": "kavitha.r@example.in", "customer_tier": "low",  "amount":  399.00, "failure_reason": "bank_timeout",       "failed_at": _ts(30)},
    {"customer_id": "CUST-AMRIT-012",  "customer_name": "Amrit Singh Sandhu",    "customer_email": "amrit.s@example.in",   "customer_tier": "high", "amount": 1750.00, "failure_reason": "insufficient_funds", "failed_at": _ts(28)},
    {"customer_id": "CUST-NEHA-013",   "customer_name": "Neha Joshi",            "customer_email": "neha.j@example.in",    "customer_tier": "low",  "amount":  550.00, "failure_reason": "card_declined",      "failed_at": _ts(24)},
    {"customer_id": "CUST-KARTHIK-014","customer_name": "Karthik Balakrishnan",  "customer_email": "karthik.b@example.in", "customer_tier": "high", "amount": 3800.00, "failure_reason": "card_declined",      "failed_at": _ts(20)},
    # Non-retryable: expired card -> send payment-update link -------------
    {"customer_id": "CUST-POOJA-015",  "customer_name": "Pooja Desai",           "customer_email": "pooja.d@example.in",   "customer_tier": "low",  "amount":  899.00, "failure_reason": "expired_card",       "failed_at": _ts(18), "_note": "send_payment_update"},
    {"customer_id": "CUST-SURESH-016", "customer_name": "Suresh Iyer",           "customer_email": "suresh.i@example.in",  "customer_tier": "high", "amount": 2750.00, "failure_reason": "expired_card",       "failed_at": _ts(15)},
    # Hard skips ----------------------------------------------------------
    {"customer_id": "CUST-FATIMA-017", "customer_name": "Fatima Sheikh",         "customer_email": "fatima.s@example.in",  "customer_tier": "low",  "amount":  600.00, "failure_reason": "already_refunded",   "failed_at": _ts(12), "_note": "hard skip"},
    {"customer_id": "CUST-GAURAV-018", "customer_name": "Gaurav Tiwari",         "customer_email": "gaurav.t@example.in",  "customer_tier": "low",  "amount":  350.00, "failure_reason": "duplicate_charge",   "failed_at": _ts(10), "_note": "hard skip"},
    # Below cost floor + retry_count=2 -> skip_cost_floor ----------------
    {"customer_id": "CUST-MANI-019",   "customer_name": "Mani Chandrasekaran",   "customer_email": "mani.c@example.in",    "customer_tier": "low",  "amount":   90.00, "failure_reason": "card_declined",      "failed_at": _ts(6),  "retry_count": 2, "_note": "skip_cost_floor"},
    # Zero amount -> skip_invalid_data ------------------------------------
    {"customer_id": "CUST-LEENA-020",  "customer_name": "Leena Fernandes",       "customer_email": "leena.f@example.in",   "customer_tier": "low",  "amount":    0.00, "failure_reason": "card_declined",      "failed_at": _ts(2),  "_note": "skip_invalid_data"},
]


def main():
    if not MERCHANT_ID:
        print(
            "\n[ERROR] SEED_MERCHANT_ID is not set.\n"
            "Set it before running:\n"
            "  $env:SEED_MERCHANT_ID = '<your-merchant-uuid>'\n"
            "  python scripts/seed_demo_data.py\n\n"
            "Find your merchant UUID: Supabase -> Table Editor -> merchants -> id column."
        )
        sys.exit(1)

    print(f"\n{'='*65}")
    print(f"  SEED DEMO DATA  ->  {WEBHOOK_URL}")
    print(f"  Merchant : {MERCHANT_ID}")
    print(f"  Records  : {len(SEED_RECORDS)}")
    print(f"{'='*65}\n")

    counts = {"success": 0, "skipped": 0, "failed": 0, "error": 0}

    for i, rec in enumerate(SEED_RECORDS, 1):
        note    = rec.pop("_note", "")
        payload = {
            "merchant_id":    MERCHANT_ID,
            "customer_id":    rec["customer_id"],
            "customer_name":  rec["customer_name"],
            "customer_email": rec["customer_email"],
            "customer_tier":  rec.get("customer_tier", "low"),
            "amount":         rec["amount"],
            "failure_reason": rec["failure_reason"],
        }
        try:
            resp = requests.post(
                WEBHOOK_URL,
                json=payload,
                timeout=30,
                headers={"X-Razorpay-Signature": "mock"},
            )
            resp.raise_for_status()
            data    = resp.json()
            outcome = data.get("result", {}).get("execution", {}).get("outcome", "?")
            action  = data.get("result", {}).get("decision", {}).get("action", "?")
            icon    = {"success": "OK", "skipped": "--", "failed": "!!"}.get(outcome, "??")
            counts[outcome if outcome in counts else "error"] += 1
            print(
                f"  [{i:02d}/{len(SEED_RECORDS)}] [{icon}] "
                f"{rec['customer_name']:<26} "
                f"{rec['failure_reason']:<22} "
                f"Rs{rec['amount']:>8.2f}  ->  {action:<30} ({outcome})"
            )
            if note:
                print(f"         note: {note}")
        except requests.RequestException as exc:
            counts["error"] += 1
            print(f"  [{i:02d}/{len(SEED_RECORDS)}] [ERR] {rec['customer_name']} -- {exc}")

        time.sleep(0.35)

    eligible = counts["success"] + counts["failed"]
    rate     = round(counts["success"] / max(eligible, 1) * 100, 1)

    print(f"\n{'='*65}")
    print(f"  Recovered : {counts['success']}")
    print(f"  Skipped   : {counts['skipped']}")
    print(f"  Failed    : {counts['failed']}")
    print(f"  Errors    : {counts['error']}")
    print(f"  Recovery rate (excl. skips): {rate}%")
    print(f"{'='*65}\n")

    if counts["error"]:
        print(
            "Some requests errored. Check:\n"
            "  1. FastAPI is running (uvicorn backend.main:app --port 8000)\n"
            "  2. SEED_API_URL is correct if not localhost:8000\n"
            "  3. SEED_MERCHANT_ID is a valid UUID in your merchants table\n"
        )


if __name__ == "__main__":
    main()
